webservers:
  hosts:
    rb-web-use-1a:
      ansible_host: 192.168.30.20
    rb-web-use-1b:
      ansible_host: 192.168.30.71
    rb-web-use-1c:
      ansible_host: 192.168.30.117

appservers:
  hosts:
    rb-app-use-1a:
      ansible_host: 192.168.30.45
    rb-app-use-1b:
      ansible_host: 192.168.30.94
    rb-app-use-1c:
      ansible_host: 192.168.30.136

databases:
  hosts:
    rb-db-use-1a:
      ansible_host: 192.168.30.60
    rb-db-use-1b:
      ansible_host: 192.168.30.101
    rb-db-use-1c:
      ansible_host: 192.168.30.149

rocketbank-aws:
  children:
    webservers:
    appservers:
    databases:
  vars:
    ansible_user: ec2-user
    ansible_private_key_file: rb.pem