name: 'Rocket Bank Cloud Infrastructure: AWS Deployment Pipeline'
run-name: ${{ github.actor }} has triggered the pipeline

on:
  push:
    branches: ["main"]

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform CLI'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    
    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3.1.1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -recursive -check

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terrafrom Apply
        if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false