name: 'Rocket Bank Cloud Infrastructure: AWS Deployment Pipeline'

on:
  pull_request_target:
    types:
      - closed
  

permissions:
  contents: read

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    name: 'Terraform CLI'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    
    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3.1.1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false