name: 'Rocket Bank Cloud Infrastructure: Terraform Fmt Check and Validate'
run-name: ${{ github.actor }} has triggered the pipeline

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: ["main"]

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: 'Terraform CLI'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_URL: ${{ github.event.pull_request.html_url }}

    defaults:
      run:
        shell: bash
    
    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3.1.1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: |
          terraform fmt -check -recursive

      - name: Successful Format Check
        if: success()
        run: |
          gh pr comment $PR_URL --body "Successful Terraform Format Check"

      - name: PR Comment fmt-logs on Failure
        if: failure()
        run: |
          echo "FAIL: Format Check" > fmt-logs.txt
          terraform fmt -check -recursive | tee -a fmt-logs.txt
          echo "I made it here"
          gh pr comment $PR_URL --body "\`\`\`$(cat fmt-logs.txt)\`\`\`"
          exit 2

      - name: Terraform Validate
        continue-on-error: true
        run: |
          echo "FAIL: Validate Check" > validate.txt
          terraform validate -no-color 2>&1 | tee -a validate.txt
          if grep "Error" validate.txt; then return 1; else return 0; fi

      - name: Successful Validate Check
        if: success()
        run: |
          gh pr comment $PR_URL --body "Successful Terraform Validate Check"

      - name: PR Comment validate logs on Failure
        if: failure()
        run: |
          cat validate.txt
          gh pr comment $PR_URL --body "```${cat validate.txt}```" && return 2

      - name: Terraform Plan
        run: |
          echo "FAIL: Plan Check" > plan.txt
          terraform plan -no-color -input=false 2>&1 | tee -a plan.txt
          if grep "Error" plan.txt; then return 2; else return 0; fi
      
      - name: Successful Plan
        if: success()
        run: |
          gh pr comment $PR_URL --body "Successful Terraform Plan"

      - name: PR comment plan logs on failure
        if: failure()
        run: |
          awk '/Error:/,/╵/ {print}' plan.txt >> exlogs.txt
          gh pr comment $PR_URL --body "```${cat exlogs.txt}```" && return 2